library(devtools)

install_github('HaoLi111/rglUtils')
install_github('HaoLi111/rgrUtils')
install_github('HaoLi111/rVividImg')
install_github('HaoLi111/AutoVisi')
#install.packages('GGally')
#install.packages('tiff')
#install.packages('plot3Drgl')
library(AutoVisi)
library(rgrUtils)
library(rglUtils)
library(rVividImg)
vmap(iris,v_mvdf)
